### PR TITLE
Create a Function

### PR DESCRIPTION
**Pull request by HugsGaming**

### CODE REVIEW

**Review by sitiom — APPROVED** [review]
I approve this

**Comment by Melonator** [comment]
Lgtm!

**Comment by thekovie** [comment]
lgtm i love it! But it's a **no for me**.

image

**Comment by MiguelRobles7** [comment]
yo I just woke up but this pr was missing something my idols, I recommend looking at [this repository](https://github.com/Externalizable/bongo.cat) for references

**Comment by MiguelRobles7** [comment]
Another good reference you can use for this pr [here](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Pull request merged**
